/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gabri
 */
public class TelaCorrecaoPotassio extends javax.swing.JFrame {

    /**
     * Creates new form CorrecaoPotassio
     */
    public TelaCorrecaoPotassio() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtParticipacaoAtual = new javax.swing.JLabel();
        cxParticipacaoAtual = new javax.swing.JTextField();
        rtUnidadeParticipacaoAtual = new javax.swing.JLabel();
        rtParticipacaoDesejada = new javax.swing.JLabel();
        cxParticipacaoDesejada = new javax.swing.JTextField();
        rtUnidadeParticipacaodesejada = new javax.swing.JLabel();
        rtParticipacaoIdeal = new javax.swing.JLabel();
        cxParticipacaoIdeal = new javax.swing.JTextField();
        rtUnidadeParticipacaoIdeal = new javax.swing.JLabel();
        rtFontePotassio = new javax.swing.JLabel();
        rtQuantidadeAplicar = new javax.swing.JLabel();
        cxQuantidadeAplicar = new javax.swing.JTextField();
        rtUnidadeQuantidadeAplicar = new javax.swing.JLabel();
        rtCusto = new javax.swing.JLabel();
        cxCusto = new javax.swing.JTextField();
        rtValorFonte = new javax.swing.JLabel();
        cxValorFonte = new javax.swing.JTextField();
        rtCorrecao = new javax.swing.JLabel();
        cxCorrecaoAdicional = new javax.swing.JTextField();
        cxFonte = new javax.swing.JTextField();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Correção Potássio");
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        rtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        rtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtTitulo.setText("Correção Potássio");
        rtTitulo.setPreferredSize(new java.awt.Dimension(450, 100));
        getContentPane().add(rtTitulo);
        rtTitulo.setBounds(287, 50, 450, 100);

        rtParticipacaoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoAtual.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoAtual.setText("Participação atual do POTÁSSIO na CTC do solo: ");
        getContentPane().add(rtParticipacaoAtual);
        rtParticipacaoAtual.setBounds(190, 223, 389, 25);

        cxParticipacaoAtual.setEditable(false);
        cxParticipacaoAtual.setBackground(new java.awt.Color(204, 204, 204));
        cxParticipacaoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoAtual.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoAtual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxParticipacaoAtual);
        cxParticipacaoAtual.setBounds(609, 220, 200, 30);

        rtUnidadeParticipacaoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoAtual.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoAtual.setText("%");
        getContentPane().add(rtUnidadeParticipacaoAtual);
        rtUnidadeParticipacaoAtual.setBounds(827, 223, 15, 25);

        rtParticipacaoDesejada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoDesejada.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoDesejada.setText("Participação do POTÁSSIO na CTC, desejada: ");
        getContentPane().add(rtParticipacaoDesejada);
        rtParticipacaoDesejada.setBounds(190, 271, 359, 25);

        cxParticipacaoDesejada.setEditable(false);
        cxParticipacaoDesejada.setBackground(new java.awt.Color(204, 204, 204));
        cxParticipacaoDesejada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoDesejada.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoDesejada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxParticipacaoDesejada);
        cxParticipacaoDesejada.setBounds(609, 268, 200, 30);

        rtUnidadeParticipacaodesejada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaodesejada.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaodesejada.setText("%");
        getContentPane().add(rtUnidadeParticipacaodesejada);
        rtUnidadeParticipacaodesejada.setBounds(827, 271, 15, 25);

        rtParticipacaoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoIdeal.setText("Participação ideal do POTÁSSIO na CTC: ");
        getContentPane().add(rtParticipacaoIdeal);
        rtParticipacaoIdeal.setBounds(190, 319, 322, 25);

        cxParticipacaoIdeal.setEditable(false);
        cxParticipacaoIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxParticipacaoIdeal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cxParticipacaoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxParticipacaoIdeal.setText("3,0");
        getContentPane().add(cxParticipacaoIdeal);
        cxParticipacaoIdeal.setBounds(609, 316, 200, 30);

        rtUnidadeParticipacaoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoIdeal.setText("%");
        getContentPane().add(rtUnidadeParticipacaoIdeal);
        rtUnidadeParticipacaoIdeal.setBounds(827, 319, 15, 25);

        rtFontePotassio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtFontePotassio.setForeground(new java.awt.Color(0, 0, 0));
        rtFontePotassio.setText("Fonte de POTÁSSIO a usar: ");
        getContentPane().add(rtFontePotassio);
        rtFontePotassio.setBounds(190, 367, 220, 25);

        rtQuantidadeAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtQuantidadeAplicar.setForeground(new java.awt.Color(0, 0, 0));
        rtQuantidadeAplicar.setText("Quantidade a aplicar:");
        getContentPane().add(rtQuantidadeAplicar);
        rtQuantidadeAplicar.setBounds(190, 415, 167, 25);

        cxQuantidadeAplicar.setEditable(false);
        cxQuantidadeAplicar.setBackground(new java.awt.Color(204, 204, 204));
        cxQuantidadeAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxQuantidadeAplicar.setForeground(new java.awt.Color(0, 0, 0));
        cxQuantidadeAplicar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxQuantidadeAplicar);
        cxQuantidadeAplicar.setBounds(609, 412, 200, 30);

        rtUnidadeQuantidadeAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeQuantidadeAplicar.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeQuantidadeAplicar.setText("kg/hectare");
        getContentPane().add(rtUnidadeQuantidadeAplicar);
        rtUnidadeQuantidadeAplicar.setBounds(827, 415, 84, 25);

        rtCusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtCusto.setForeground(new java.awt.Color(0, 0, 0));
        rtCusto.setText("Custo - R$/ha");
        getContentPane().add(rtCusto);
        rtCusto.setBounds(190, 463, 110, 25);

        cxCusto.setEditable(false);
        cxCusto.setBackground(new java.awt.Color(204, 204, 204));
        cxCusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxCusto.setForeground(new java.awt.Color(0, 0, 0));
        cxCusto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxCusto);
        cxCusto.setBounds(609, 460, 200, 30);

        rtValorFonte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtValorFonte.setForeground(new java.awt.Color(0, 0, 0));
        rtValorFonte.setText("Valor/Ton (R$)");
        getContentPane().add(rtValorFonte);
        rtValorFonte.setBounds(770, 367, 90, 20);

        cxValorFonte.setEditable(false);
        cxValorFonte.setBackground(new java.awt.Color(204, 204, 204));
        cxValorFonte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxValorFonte.setForeground(new java.awt.Color(0, 0, 0));
        cxValorFonte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxValorFonte);
        cxValorFonte.setBounds(870, 364, 120, 30);

        rtCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtCorrecao.setText("Essa correção de POTÁSSIO, fornecerá também (kg/ha):");
        getContentPane().add(rtCorrecao);
        rtCorrecao.setBounds(190, 542, 320, 16);

        cxCorrecaoAdicional.setEditable(false);
        cxCorrecaoAdicional.setBackground(new java.awt.Color(204, 204, 204));
        cxCorrecaoAdicional.setForeground(new java.awt.Color(0, 0, 0));
        cxCorrecaoAdicional.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxCorrecaoAdicional.setPreferredSize(new java.awt.Dimension(70, 30));
        getContentPane().add(cxCorrecaoAdicional);
        cxCorrecaoAdicional.setBounds(510, 535, 300, 32);

        cxFonte.setEditable(false);
        cxFonte.setBackground(new java.awt.Color(204, 204, 204));
        cxFonte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxFonte.setForeground(new java.awt.Color(0, 0, 0));
        cxFonte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxFonte.setPreferredSize(new java.awt.Dimension(256, 31));
        getContentPane().add(cxFonte);
        cxFonte.setBounds(509, 364, 250, 30);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 2\\Arquitetura de Software\\soilcorrectionCompleto\\soilcorrection\\src\\main\\java\\imagens\\background.png")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(-10, -10, 1050, 790);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void mostrarCorrecaoPotassio(DadosCorrecaoPotassio dados){
        if(dados.getNecessidadeCorrecao() <= 0){
            cxParticipacaoAtual.setText(Double.toString(dados.getAtual()));
            cxParticipacaoDesejada.setText("Não precisa correção");
            cxFonte.setText("Não precisa correção");
            cxQuantidadeAplicar.setText("Não precisa correção");
            cxCusto.setText("Não precisa correção");
            cxCorrecaoAdicional.setText("Não precisa correção");
        }
        else{
            cxParticipacaoAtual.setText(Double.toString(dados.getAtual()));
            cxParticipacaoDesejada.setText(Double.toString(dados.getDesejada()));
            cxFonte.setText(dados.getFonte());
            cxValorFonte.setText(Double.toString(dados.getValor()));
            cxQuantidadeAplicar.setText(Double.toString(dados.getQtdAplicar()));
            cxCusto.setText(Double.toString(dados.getCusto()));
            if(dados.getNomeAdicional().length() >0 && dados.getNomeAdicional2().length() > 0){
                cxCorrecaoAdicional.setText(
                        dados.getNomeAdicional()+": "
                        +Double.toString(dados.getValorAdicional())+" e "
                        +dados.getNomeAdicional2()+": "
                        +Double.toString(dados.getValorAdicional2()));
            }
            if(dados.getNomeAdicional().length() >0 && dados.getNomeAdicional2().length() <= 0){
                cxCorrecaoAdicional.setText(dados.getNomeAdicional()+": "+Double.toString(dados.getValorAdicional()));
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCorrecaoPotassio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCorrecaoPotassio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCorrecaoPotassio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCorrecaoPotassio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCorrecaoPotassio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxCorrecaoAdicional;
    private javax.swing.JTextField cxCusto;
    private javax.swing.JTextField cxFonte;
    private javax.swing.JTextField cxParticipacaoAtual;
    private javax.swing.JTextField cxParticipacaoDesejada;
    private javax.swing.JTextField cxParticipacaoIdeal;
    private javax.swing.JTextField cxQuantidadeAplicar;
    private javax.swing.JTextField cxValorFonte;
    private javax.swing.JLabel rtCorrecao;
    private javax.swing.JLabel rtCusto;
    private javax.swing.JLabel rtFontePotassio;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtParticipacaoAtual;
    private javax.swing.JLabel rtParticipacaoDesejada;
    private javax.swing.JLabel rtParticipacaoIdeal;
    private javax.swing.JLabel rtQuantidadeAplicar;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtUnidadeParticipacaoAtual;
    private javax.swing.JLabel rtUnidadeParticipacaoIdeal;
    private javax.swing.JLabel rtUnidadeParticipacaodesejada;
    private javax.swing.JLabel rtUnidadeQuantidadeAplicar;
    private javax.swing.JLabel rtValorFonte;
    // End of variables declaration//GEN-END:variables

}
