/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.telas;

import static java.awt.event.KeyEvent.VK_ENTER;

/**
 *
 * @author gabri
 */
public class CorrecaoCalcioMagnesioGUI extends javax.swing.JFrame {

    /**
     * Creates new form CorreçãoCalcioMagnesio
     */
    public CorrecaoCalcioMagnesioGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtCalcio = new javax.swing.JLabel();
        rtParticipacaoAtual = new javax.swing.JLabel();
        cxParticipacaoAtual = new javax.swing.JTextField();
        rtUnidadeParticipacaoAtual = new javax.swing.JLabel();
        rtParticipacaoIdeal = new javax.swing.JLabel();
        cxParticipacaoIdeal = new javax.swing.JTextField();
        rtUnidadeParticipacaoIdeal = new javax.swing.JLabel();
        rtParticipacaoCorrecao = new javax.swing.JLabel();
        cxParticipacaoCorrecao = new javax.swing.JTextField();
        rtUnidadeParticipacaoCorrecao = new javax.swing.JLabel();
        rtPorcentParticipacao = new javax.swing.JLabel();
        cxPorcentParticipacao = new javax.swing.JTextField();
        rtUnidadePorcentParticipacao = new javax.swing.JLabel();
        rtMagnesio = new javax.swing.JLabel();
        rtParticipacaoAtual1 = new javax.swing.JLabel();
        cxParticipacaoAtual1 = new javax.swing.JTextField();
        rtUnidadeParticipacaoAtual1 = new javax.swing.JLabel();
        rtParticipacaoIdeal1 = new javax.swing.JLabel();
        cxParticipacaoIdeal1 = new javax.swing.JTextField();
        rtUnidadeParticipacaoIdeal1 = new javax.swing.JLabel();
        rtParticipacaoCorrecao1 = new javax.swing.JLabel();
        cxParticipacaoCorrecao1 = new javax.swing.JTextField();
        rtUnidadeParticipacaoCorrecao1 = new javax.swing.JLabel();
        rtFonteCorretivo = new javax.swing.JLabel();
        cbFonteCorretivo = new javax.swing.JComboBox<>();
        rtPRNT = new javax.swing.JLabel();
        cxPRNT = new javax.swing.JTextField();
        rtUnidadePRNT = new javax.swing.JLabel();
        rtTeorCao = new javax.swing.JLabel();
        cxTeorCao = new javax.swing.JTextField();
        rtUnidadeTeorCao = new javax.swing.JLabel();
        rtQuantidadeAplicar = new javax.swing.JLabel();
        cxQuantidadeAplicar = new javax.swing.JTextField();
        rtUnidadeQuantidadeaplicar = new javax.swing.JLabel();
        rtCusto = new javax.swing.JLabel();
        cxCusto = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Correção Cálcio Magnésio");
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        rtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        rtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtTitulo.setText("Correção Cálcio Magnésio");
        rtTitulo.setPreferredSize(new java.awt.Dimension(600, 75));
        getContentPane().add(rtTitulo);
        rtTitulo.setBounds(212, 6, 600, 75);

        rtCalcio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtCalcio.setForeground(new java.awt.Color(0, 0, 0));
        rtCalcio.setText("Cálcio");
        getContentPane().add(rtCalcio);
        rtCalcio.setBounds(125, 99, 51, 25);

        rtParticipacaoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoAtual.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoAtual.setText("Participação atual na CTC do solo:");
        getContentPane().add(rtParticipacaoAtual);
        rtParticipacaoAtual.setBounds(125, 145, 268, 25);

        cxParticipacaoAtual.setEditable(false);
        cxParticipacaoAtual.setBackground(new java.awt.Color(153, 153, 153));
        cxParticipacaoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoAtual.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoAtual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxParticipacaoAtual);
        cxParticipacaoAtual.setBounds(411, 142, 150, 30);

        rtUnidadeParticipacaoAtual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoAtual.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoAtual.setText("%");
        getContentPane().add(rtUnidadeParticipacaoAtual);
        rtUnidadeParticipacaoAtual.setBounds(579, 145, 15, 25);

        rtParticipacaoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoIdeal.setText("Ideal:");
        getContentPane().add(rtParticipacaoIdeal);
        rtParticipacaoIdeal.setBounds(125, 380, 42, 25);

        cxParticipacaoIdeal.setEditable(false);
        cxParticipacaoIdeal.setBackground(new java.awt.Color(153, 153, 153));
        cxParticipacaoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxParticipacaoIdeal.setText("45% a 55%");
        getContentPane().add(cxParticipacaoIdeal);
        cxParticipacaoIdeal.setBounds(185, 190, 150, 30);

        rtUnidadeParticipacaoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoIdeal.setText("%");
        getContentPane().add(rtUnidadeParticipacaoIdeal);
        rtUnidadeParticipacaoIdeal.setBounds(353, 193, 15, 25);

        rtParticipacaoCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoCorrecao.setText("Após as correções");
        getContentPane().add(rtParticipacaoCorrecao);
        rtParticipacaoCorrecao.setBounds(411, 193, 145, 25);

        cxParticipacaoCorrecao.setEditable(false);
        cxParticipacaoCorrecao.setBackground(new java.awt.Color(153, 153, 153));
        cxParticipacaoCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoCorrecao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxParticipacaoCorrecao);
        cxParticipacaoCorrecao.setBounds(574, 190, 150, 30);

        rtUnidadeParticipacaoCorrecao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoCorrecao.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoCorrecao.setText("%");
        getContentPane().add(rtUnidadeParticipacaoCorrecao);
        rtUnidadeParticipacaoCorrecao.setBounds(742, 193, 15, 25);

        rtPorcentParticipacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtPorcentParticipacao.setForeground(new java.awt.Color(0, 0, 0));
        rtPorcentParticipacao.setText("% de participação de Cálcio na CTC, desejada:");
        getContentPane().add(rtPorcentParticipacao);
        rtPorcentParticipacao.setBounds(125, 241, 361, 25);

        cxPorcentParticipacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxPorcentParticipacao.setForeground(new java.awt.Color(0, 0, 0));
        cxPorcentParticipacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPorcentParticipacao);
        cxPorcentParticipacao.setBounds(504, 238, 150, 30);

        rtUnidadePorcentParticipacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadePorcentParticipacao.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadePorcentParticipacao.setText("%");
        getContentPane().add(rtUnidadePorcentParticipacao);
        rtUnidadePorcentParticipacao.setBounds(672, 241, 15, 25);

        rtMagnesio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtMagnesio.setForeground(new java.awt.Color(0, 0, 0));
        rtMagnesio.setText("Magnésio");
        getContentPane().add(rtMagnesio);
        rtMagnesio.setBounds(125, 286, 83, 25);

        rtParticipacaoAtual1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoAtual1.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoAtual1.setText("Participação atual na CTC do solo:");
        getContentPane().add(rtParticipacaoAtual1);
        rtParticipacaoAtual1.setBounds(125, 332, 268, 25);

        cxParticipacaoAtual1.setEditable(false);
        cxParticipacaoAtual1.setBackground(new java.awt.Color(153, 153, 153));
        cxParticipacaoAtual1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoAtual1.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoAtual1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxParticipacaoAtual1);
        cxParticipacaoAtual1.setBounds(411, 329, 150, 30);

        rtUnidadeParticipacaoAtual1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoAtual1.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoAtual1.setText("%");
        getContentPane().add(rtUnidadeParticipacaoAtual1);
        rtUnidadeParticipacaoAtual1.setBounds(579, 332, 15, 25);

        rtParticipacaoIdeal1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoIdeal1.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoIdeal1.setText("Ideal:");
        getContentPane().add(rtParticipacaoIdeal1);
        rtParticipacaoIdeal1.setBounds(125, 193, 42, 25);

        cxParticipacaoIdeal1.setEditable(false);
        cxParticipacaoIdeal1.setBackground(new java.awt.Color(153, 153, 153));
        cxParticipacaoIdeal1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoIdeal1.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoIdeal1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxParticipacaoIdeal1.setText("10% a 15%");
        getContentPane().add(cxParticipacaoIdeal1);
        cxParticipacaoIdeal1.setBounds(185, 377, 150, 30);

        rtUnidadeParticipacaoIdeal1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoIdeal1.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoIdeal1.setText("%");
        getContentPane().add(rtUnidadeParticipacaoIdeal1);
        rtUnidadeParticipacaoIdeal1.setBounds(353, 380, 15, 25);

        rtParticipacaoCorrecao1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtParticipacaoCorrecao1.setForeground(new java.awt.Color(0, 0, 0));
        rtParticipacaoCorrecao1.setText("Após as correções");
        getContentPane().add(rtParticipacaoCorrecao1);
        rtParticipacaoCorrecao1.setBounds(411, 380, 145, 25);

        cxParticipacaoCorrecao1.setEditable(false);
        cxParticipacaoCorrecao1.setBackground(new java.awt.Color(153, 153, 153));
        cxParticipacaoCorrecao1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxParticipacaoCorrecao1.setForeground(new java.awt.Color(0, 0, 0));
        cxParticipacaoCorrecao1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxParticipacaoCorrecao1);
        cxParticipacaoCorrecao1.setBounds(574, 377, 150, 30);

        rtUnidadeParticipacaoCorrecao1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeParticipacaoCorrecao1.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeParticipacaoCorrecao1.setText("%");
        getContentPane().add(rtUnidadeParticipacaoCorrecao1);
        rtUnidadeParticipacaoCorrecao1.setBounds(742, 380, 15, 25);

        rtFonteCorretivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtFonteCorretivo.setForeground(new java.awt.Color(0, 0, 0));
        rtFonteCorretivo.setText("Fonte de corretivo a usar:");
        getContentPane().add(rtFonteCorretivo);
        rtFonteCorretivo.setBounds(125, 444, 201, 25);

        cbFonteCorretivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbFonteCorretivo.setForeground(new java.awt.Color(0, 0, 0));
        cbFonteCorretivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calcário Dolomítico", "Calcário Calcítico", "Calcário de Concha", "Gesso Agrícola", "Hidróxido de Cálcio", "Calcário Magnesiano" }));
        getContentPane().add(cbFonteCorretivo);
        cbFonteCorretivo.setBounds(344, 441, 200, 30);

        rtPRNT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtPRNT.setForeground(new java.awt.Color(0, 0, 0));
        rtPRNT.setText("PRNT:");
        getContentPane().add(rtPRNT);
        rtPRNT.setBounds(125, 492, 47, 25);

        cxPRNT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxPRNT.setForeground(new java.awt.Color(0, 0, 0));
        cxPRNT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPRNT);
        cxPRNT.setBounds(190, 489, 150, 30);

        rtUnidadePRNT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadePRNT.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadePRNT.setText("%");
        getContentPane().add(rtUnidadePRNT);
        rtUnidadePRNT.setBounds(358, 492, 15, 25);

        rtTeorCao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtTeorCao.setForeground(new java.awt.Color(0, 0, 0));
        rtTeorCao.setText("Teor de CaO do corretivo:");
        getContentPane().add(rtTeorCao);
        rtTeorCao.setBounds(125, 540, 205, 25);

        cxTeorCao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxTeorCao.setForeground(new java.awt.Color(0, 0, 0));
        cxTeorCao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxTeorCao);
        cxTeorCao.setBounds(348, 537, 150, 30);

        rtUnidadeTeorCao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeTeorCao.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeTeorCao.setText("%");
        getContentPane().add(rtUnidadeTeorCao);
        rtUnidadeTeorCao.setBounds(516, 540, 15, 25);

        rtQuantidadeAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtQuantidadeAplicar.setForeground(new java.awt.Color(0, 0, 0));
        rtQuantidadeAplicar.setText("Quantidade a aplicar:");
        getContentPane().add(rtQuantidadeAplicar);
        rtQuantidadeAplicar.setBounds(125, 588, 167, 25);

        cxQuantidadeAplicar.setEditable(false);
        cxQuantidadeAplicar.setBackground(new java.awt.Color(153, 153, 153));
        cxQuantidadeAplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxQuantidadeAplicar.setForeground(new java.awt.Color(0, 0, 0));
        cxQuantidadeAplicar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxQuantidadeAplicar);
        cxQuantidadeAplicar.setBounds(310, 585, 150, 30);

        rtUnidadeQuantidadeaplicar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeQuantidadeaplicar.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeQuantidadeaplicar.setText("Ton./ha");
        getContentPane().add(rtUnidadeQuantidadeaplicar);
        rtUnidadeQuantidadeaplicar.setBounds(478, 588, 60, 25);

        rtCusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtCusto.setForeground(new java.awt.Color(0, 0, 0));
        rtCusto.setText("Custo - R$/ha:");
        getContentPane().add(rtCusto);
        rtCusto.setBounds(125, 636, 114, 25);

        cxCusto.setEditable(false);
        cxCusto.setBackground(new java.awt.Color(153, 153, 153));
        cxCusto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxCusto.setForeground(new java.awt.Color(0, 0, 0));
        cxCusto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxCusto);
        cxCusto.setBounds(257, 633, 150, 30);

        btEnviar.setBackground(new java.awt.Color(255, 255, 255));
        btEnviar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btEnviar.setForeground(new java.awt.Color(0, 0, 0));
        btEnviar.setText("Enviar");
        btEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEnviar.setPreferredSize(new java.awt.Dimension(84, 42));
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });
        btEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btEnviarKeyPressed(evt);
            }
        });
        getContentPane().add(btEnviar);
        btEnviar.setBounds(705, 575, 160, 50);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 2\\Arquitetura de Software\\GUIsoilcorrection\\GUIsoilcorrection\\src\\main\\java\\gui\\imagens\\fundo3.jpg")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(0, 0, 1090, 780);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        String desejada = cxPorcentParticipacao.getText();
        String fonte = cbFonteCorretivo.getSelectedItem().toString();
        String prnt = cxPRNT.getText();
        String teorCao = cxTeorCao.getText();
        
        enviar(desejada, fonte, prnt, teorCao);
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btEnviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btEnviarKeyPressed
        String desejada = cxPorcentParticipacao.getText();
        String fonte = cbFonteCorretivo.getSelectedItem().toString();
        String prnt = cxPRNT.getText();
        String teorCao = cxTeorCao.getText();
        
        if(evt.getKeyCode() == VK_ENTER){
            enviar(desejada, fonte, prnt, teorCao);
        }
    }//GEN-LAST:event_btEnviarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorrecaoCalcioMagnesioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorrecaoCalcioMagnesioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorrecaoCalcioMagnesioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorrecaoCalcioMagnesioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorrecaoCalcioMagnesioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JComboBox<String> cbFonteCorretivo;
    private javax.swing.JTextField cxCusto;
    private javax.swing.JTextField cxPRNT;
    private javax.swing.JTextField cxParticipacaoAtual;
    private javax.swing.JTextField cxParticipacaoAtual1;
    private javax.swing.JTextField cxParticipacaoCorrecao;
    private javax.swing.JTextField cxParticipacaoCorrecao1;
    private javax.swing.JTextField cxParticipacaoIdeal;
    private javax.swing.JTextField cxParticipacaoIdeal1;
    private javax.swing.JTextField cxPorcentParticipacao;
    private javax.swing.JTextField cxQuantidadeAplicar;
    private javax.swing.JTextField cxTeorCao;
    private javax.swing.JLabel rtCalcio;
    private javax.swing.JLabel rtCusto;
    private javax.swing.JLabel rtFonteCorretivo;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtMagnesio;
    private javax.swing.JLabel rtPRNT;
    private javax.swing.JLabel rtParticipacaoAtual;
    private javax.swing.JLabel rtParticipacaoAtual1;
    private javax.swing.JLabel rtParticipacaoCorrecao;
    private javax.swing.JLabel rtParticipacaoCorrecao1;
    private javax.swing.JLabel rtParticipacaoIdeal;
    private javax.swing.JLabel rtParticipacaoIdeal1;
    private javax.swing.JLabel rtPorcentParticipacao;
    private javax.swing.JLabel rtQuantidadeAplicar;
    private javax.swing.JLabel rtTeorCao;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtUnidadePRNT;
    private javax.swing.JLabel rtUnidadeParticipacaoAtual;
    private javax.swing.JLabel rtUnidadeParticipacaoAtual1;
    private javax.swing.JLabel rtUnidadeParticipacaoCorrecao;
    private javax.swing.JLabel rtUnidadeParticipacaoCorrecao1;
    private javax.swing.JLabel rtUnidadeParticipacaoIdeal;
    private javax.swing.JLabel rtUnidadeParticipacaoIdeal1;
    private javax.swing.JLabel rtUnidadePorcentParticipacao;
    private javax.swing.JLabel rtUnidadeQuantidadeaplicar;
    private javax.swing.JLabel rtUnidadeTeorCao;
    // End of variables declaration//GEN-END:variables

    public String enviar(String desejado, String fonte, String prnt, String teorCao) {
        cxPorcentParticipacao.setText(desejado);
        cbFonteCorretivo.setSelectedItem(fonte);
        cxPRNT.setText(prnt);
        cxTeorCao.setText(teorCao);
        cxParticipacaoAtual.setText("44.7");
        cxParticipacaoCorrecao.setText("44.7");
        cxParticipacaoAtual1.setText("12.6");
        cxParticipacaoCorrecao1.setText("12.6");
        cxQuantidadeAplicar.setText("0.00");
        cxCusto.setText("0.00");
        
        return cxPorcentParticipacao.getText()+" "+cbFonteCorretivo.getSelectedItem().toString()+" "+cxPRNT.getText()+" "+
                cxTeorCao.getText()+" "+cxParticipacaoAtual.getText()+" "+cxParticipacaoCorrecao.getText()+" "+
                cxParticipacaoAtual1.getText()+" "+cxParticipacaoCorrecao1.getText()+" "+
                cxQuantidadeAplicar.getText()+" "+cxCusto.getText();
    }
}
