/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.telas;

/**
 *
 * @author gabri
 */
public class InformacoesUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InformacoesUsuario
     */
    public InformacoesUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtProdutor = new javax.swing.JLabel();
        cxProdutor = new javax.swing.JTextField();
        rtData = new javax.swing.JLabel();
        cxData = new javax.swing.JTextField();
        rtMunicipio = new javax.swing.JLabel();
        cxMunicipio = new javax.swing.JTextField();
        rtLote = new javax.swing.JLabel();
        cxLote = new javax.swing.JTextField();
        rtAreaTotal = new javax.swing.JLabel();
        cxAreaTotal = new javax.swing.JTextField();
        rtTalhao = new javax.swing.JLabel();
        cxTalhao = new javax.swing.JTextField();
        rtAreaTalhao = new javax.swing.JLabel();
        cxareaTalhao = new javax.swing.JTextField();
        rtMatriculaLote = new javax.swing.JLabel();
        cxMatriculaLote = new javax.swing.JTextField();
        rtTexturaSolo = new javax.swing.JLabel();
        cbTexturaSolo = new javax.swing.JComboBox<>();
        cxPorcentArgilaSolo = new javax.swing.JTextField();
        rtSistemaCultivo = new javax.swing.JLabel();
        cbSistemaCultivo = new javax.swing.JComboBox<>();
        rtResponsavel = new javax.swing.JLabel();
        cxResponsavel = new javax.swing.JTextField();
        rtProfundidade = new javax.swing.JLabel();
        cxProfundidade = new javax.swing.JTextField();
        rtUnidadeProfundidade = new javax.swing.JLabel();
        rtResultado = new javax.swing.JLabel();
        cxResultado = new javax.swing.JTextField();
        btEnviar = new javax.swing.JButton();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equilíbrio e Correção do Solo");
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        rtProdutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtProdutor.setForeground(new java.awt.Color(0, 0, 0));
        rtProdutor.setText("Produtor :");
        getContentPane().add(rtProdutor);
        rtProdutor.setBounds(60, 68, 80, 25);

        cxProdutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxProdutor.setForeground(new java.awt.Color(0, 0, 0));
        cxProdutor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxProdutor);
        cxProdutor.setBounds(165, 60, 350, 42);

        rtData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtData.setForeground(new java.awt.Color(0, 0, 0));
        rtData.setText("Data: ");
        getContentPane().add(rtData);
        rtData.setBounds(750, 68, 46, 25);

        cxData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxData.setForeground(new java.awt.Color(0, 0, 0));
        cxData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxData);
        cxData.setBounds(814, 60, 150, 42);

        rtMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        rtMunicipio.setText("Município: ");
        getContentPane().add(rtMunicipio);
        rtMunicipio.setBounds(60, 128, 87, 25);

        cxMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxMunicipio.setForeground(new java.awt.Color(0, 0, 0));
        cxMunicipio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxMunicipio);
        cxMunicipio.setBounds(165, 120, 350, 42);

        rtLote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtLote.setForeground(new java.awt.Color(0, 0, 0));
        rtLote.setText("Lote: ");
        getContentPane().add(rtLote);
        rtLote.setBounds(60, 188, 43, 25);

        cxLote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxLote.setForeground(new java.awt.Color(0, 0, 0));
        cxLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxLote);
        cxLote.setBounds(165, 180, 150, 42);

        rtAreaTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtAreaTotal.setForeground(new java.awt.Color(0, 0, 0));
        rtAreaTotal.setText("Área Total: (ha)");
        getContentPane().add(rtAreaTotal);
        rtAreaTotal.setBounds(678, 188, 118, 25);

        cxAreaTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxAreaTotal.setForeground(new java.awt.Color(0, 0, 0));
        cxAreaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxAreaTotal);
        cxAreaTotal.setBounds(814, 180, 150, 42);

        rtTalhao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtTalhao.setForeground(new java.awt.Color(0, 0, 0));
        rtTalhao.setText("Talhão: ");
        getContentPane().add(rtTalhao);
        rtTalhao.setBounds(60, 248, 61, 25);

        cxTalhao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxTalhao.setForeground(new java.awt.Color(0, 0, 0));
        cxTalhao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxTalhao);
        cxTalhao.setBounds(165, 240, 150, 42);

        rtAreaTalhao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtAreaTalhao.setForeground(new java.awt.Color(0, 0, 0));
        rtAreaTalhao.setText("Área do talhão: (ha)");
        getContentPane().add(rtAreaTalhao);
        rtAreaTalhao.setBounds(641, 248, 155, 25);

        cxareaTalhao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxareaTalhao.setForeground(new java.awt.Color(0, 0, 0));
        cxareaTalhao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxareaTalhao);
        cxareaTalhao.setBounds(814, 240, 150, 42);

        rtMatriculaLote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtMatriculaLote.setForeground(new java.awt.Color(0, 0, 0));
        rtMatriculaLote.setText("Matrícula do Lote: ");
        getContentPane().add(rtMatriculaLote);
        rtMatriculaLote.setBounds(60, 308, 147, 25);

        cxMatriculaLote.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxMatriculaLote.setForeground(new java.awt.Color(0, 0, 0));
        cxMatriculaLote.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxMatriculaLote);
        cxMatriculaLote.setBounds(250, 300, 150, 42);

        rtTexturaSolo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtTexturaSolo.setForeground(new java.awt.Color(0, 0, 0));
        rtTexturaSolo.setText("Textura do Solo: ");
        getContentPane().add(rtTexturaSolo);
        rtTexturaSolo.setBounds(60, 372, 134, 25);

        cbTexturaSolo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTexturaSolo.setForeground(new java.awt.Color(0, 0, 0));
        cbTexturaSolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Argiloso", "Text. Média" }));
        cbTexturaSolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTexturaSoloActionPerformed(evt);
            }
        });
        getContentPane().add(cbTexturaSolo);
        cbTexturaSolo.setBounds(250, 363, 150, 42);

        cxPorcentArgilaSolo.setEditable(false);
        cxPorcentArgilaSolo.setBackground(new java.awt.Color(153, 153, 153));
        cxPorcentArgilaSolo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxPorcentArgilaSolo.setForeground(new java.awt.Color(0, 0, 0));
        cxPorcentArgilaSolo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPorcentArgilaSolo);
        cxPorcentArgilaSolo.setBounds(418, 360, 200, 50);

        rtSistemaCultivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtSistemaCultivo.setForeground(new java.awt.Color(0, 0, 0));
        rtSistemaCultivo.setText("Sistema de Cultivo: ");
        getContentPane().add(rtSistemaCultivo);
        rtSistemaCultivo.setBounds(60, 437, 156, 25);

        cbSistemaCultivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbSistemaCultivo.setForeground(new java.awt.Color(0, 0, 0));
        cbSistemaCultivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione>", "Plantio Direto", "Convencional" }));
        getContentPane().add(cbSistemaCultivo);
        cbSistemaCultivo.setBounds(250, 428, 200, 42);

        rtResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtResponsavel.setForeground(new java.awt.Color(0, 0, 0));
        rtResponsavel.setText("Responsável Técnico: ");
        getContentPane().add(rtResponsavel);
        rtResponsavel.setBounds(60, 496, 172, 25);

        cxResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxResponsavel.setForeground(new java.awt.Color(0, 0, 0));
        cxResponsavel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxResponsavel);
        cxResponsavel.setBounds(250, 488, 150, 42);

        rtProfundidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtProfundidade.setForeground(new java.awt.Color(0, 0, 0));
        rtProfundidade.setText("Profundidade da amostra de solos: ");
        getContentPane().add(rtProfundidade);
        rtProfundidade.setBounds(60, 567, 284, 25);

        cxProfundidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxProfundidade.setForeground(new java.awt.Color(0, 0, 0));
        cxProfundidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxProfundidade);
        cxProfundidade.setBounds(362, 559, 150, 42);

        rtUnidadeProfundidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtUnidadeProfundidade.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeProfundidade.setText("cm");
        getContentPane().add(rtUnidadeProfundidade);
        rtUnidadeProfundidade.setBounds(530, 567, 24, 25);

        rtResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rtResultado.setForeground(new java.awt.Color(0, 0, 0));
        rtResultado.setText("Resultado de análise de solos: ");
        getContentPane().add(rtResultado);
        rtResultado.setBounds(60, 637, 243, 25);

        cxResultado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cxResultado.setForeground(new java.awt.Color(0, 0, 0));
        cxResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxResultado);
        cxResultado.setBounds(362, 629, 150, 42);

        btEnviar.setBackground(new java.awt.Color(255, 255, 255));
        btEnviar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btEnviar.setForeground(new java.awt.Color(0, 0, 0));
        btEnviar.setText("Enviar");
        btEnviar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btEnviar.setPreferredSize(new java.awt.Dimension(126, 63));
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btEnviar);
        btEnviar.setBounds(814, 548, 126, 63);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 2\\Arquitetura de Software\\GUIsoilcorrection\\GUIsoilcorrection\\src\\main\\java\\gui\\imagens\\fundo3.jpg")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(-10, -10, 1050, 910);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbTexturaSoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTexturaSoloActionPerformed
        if (cbTexturaSolo.getSelectedItem().toString() == "Argiloso"){
            cxPorcentArgilaSolo.setText("+ 40% de argila");
        }
        if (cbTexturaSolo.getSelectedItem().toString() == "Text. Média"){
            cxPorcentArgilaSolo.setText("25 a 40% de argila");
        }
    }//GEN-LAST:event_cbTexturaSoloActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        MenuPrincipal mp = new MenuPrincipal();
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacoesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacoesUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEnviar;
    private javax.swing.JComboBox<String> cbSistemaCultivo;
    private javax.swing.JComboBox<String> cbTexturaSolo;
    private javax.swing.JTextField cxAreaTotal;
    private javax.swing.JTextField cxData;
    private javax.swing.JTextField cxLote;
    private javax.swing.JTextField cxMatriculaLote;
    private javax.swing.JTextField cxMunicipio;
    private javax.swing.JTextField cxPorcentArgilaSolo;
    private javax.swing.JTextField cxProdutor;
    private javax.swing.JTextField cxProfundidade;
    private javax.swing.JTextField cxResponsavel;
    private javax.swing.JTextField cxResultado;
    private javax.swing.JTextField cxTalhao;
    private javax.swing.JTextField cxareaTalhao;
    private javax.swing.JLabel rtAreaTalhao;
    private javax.swing.JLabel rtAreaTotal;
    private javax.swing.JLabel rtData;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtLote;
    private javax.swing.JLabel rtMatriculaLote;
    private javax.swing.JLabel rtMunicipio;
    private javax.swing.JLabel rtProdutor;
    private javax.swing.JLabel rtProfundidade;
    private javax.swing.JLabel rtResponsavel;
    private javax.swing.JLabel rtResultado;
    private javax.swing.JLabel rtSistemaCultivo;
    private javax.swing.JLabel rtTalhao;
    private javax.swing.JLabel rtTexturaSolo;
    private javax.swing.JLabel rtUnidadeProfundidade;
    // End of variables declaration//GEN-END:variables
}
