/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.telas;

/**
 *
 * @author gabri
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btFosforo = new javax.swing.JButton();
        btCalcioMagnesio = new javax.swing.JButton();
        btPotassio = new javax.swing.JButton();
        btValoresIdeais = new javax.swing.JButton();
        rtTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Correção de Solo");
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        btFosforo.setBackground(new java.awt.Color(152, 197, 255));
        btFosforo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btFosforo.setForeground(new java.awt.Color(0, 0, 0));
        btFosforo.setText("Correção Fósforo");
        btFosforo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btFosforo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFosforoActionPerformed(evt);
            }
        });
        getContentPane().add(btFosforo);
        btFosforo.setBounds(587, 273, 300, 100);

        btCalcioMagnesio.setBackground(new java.awt.Color(152, 197, 255));
        btCalcioMagnesio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCalcioMagnesio.setForeground(new java.awt.Color(0, 0, 0));
        btCalcioMagnesio.setText("Correção Cálcio e Magnésio");
        btCalcioMagnesio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCalcioMagnesio.setPreferredSize(new java.awt.Dimension(300, 100));
        btCalcioMagnesio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcioMagnesioActionPerformed(evt);
            }
        });
        getContentPane().add(btCalcioMagnesio);
        btCalcioMagnesio.setBounds(140, 270, 300, 100);

        btPotassio.setBackground(new java.awt.Color(152, 197, 255));
        btPotassio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btPotassio.setForeground(new java.awt.Color(0, 0, 0));
        btPotassio.setText("Correção Potássio");
        btPotassio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btPotassio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPotassioActionPerformed(evt);
            }
        });
        getContentPane().add(btPotassio);
        btPotassio.setBounds(137, 473, 300, 100);

        btValoresIdeais.setBackground(new java.awt.Color(152, 197, 255));
        btValoresIdeais.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btValoresIdeais.setForeground(new java.awt.Color(0, 0, 0));
        btValoresIdeais.setText("Valores Ideais");
        btValoresIdeais.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btValoresIdeais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValoresIdeaisActionPerformed(evt);
            }
        });
        getContentPane().add(btValoresIdeais);
        btValoresIdeais.setBounds(587, 473, 300, 100);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        rtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        rtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtTitulo.setText("Correção de Solo");
        rtTitulo.setPreferredSize(new java.awt.Dimension(400, 100));
        getContentPane().add(rtTitulo);
        rtTitulo.setBounds(312, 59, 400, 100);

        jButton1.setBackground(new java.awt.Color(152, 197, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setPreferredSize(new java.awt.Dimension(84, 42));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 640, 84, 42);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 2\\Arquitetura de Software\\GUIsoilcorrection\\GUIsoilcorrection\\src\\main\\java\\gui\\imagens\\fundo.jpg")); // NOI18N
        rtFundo.setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().add(rtFundo);
        rtFundo.setBounds(0, 0, 1030, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFosforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFosforoActionPerformed
        CorrecaoFosforoGUI cf = new CorrecaoFosforoGUI();
        cf.setVisible(true);
    }//GEN-LAST:event_btFosforoActionPerformed

    private void btPotassioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPotassioActionPerformed
        CorrecaoPotassioGUI cp = new CorrecaoPotassioGUI();
        cp.setVisible(true);
    }//GEN-LAST:event_btPotassioActionPerformed

    private void btCalcioMagnesioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcioMagnesioActionPerformed
        CorrecaoCalcioMagnesioGUI ccm = new CorrecaoCalcioMagnesioGUI();
        ccm.setVisible(true);
    }//GEN-LAST:event_btCalcioMagnesioActionPerformed

    private void btValoresIdeaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValoresIdeaisActionPerformed
        ValoresIdeaisGUI vi = new ValoresIdeaisGUI();
        vi.setVisible(true);
    }//GEN-LAST:event_btValoresIdeaisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InformacoesUsuario ui = new InformacoesUsuario();
        ui.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcioMagnesio;
    private javax.swing.JButton btFosforo;
    private javax.swing.JButton btPotassio;
    private javax.swing.JButton btValoresIdeais;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtTitulo;
    // End of variables declaration//GEN-END:variables
}
