/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.telas;

import ctc.TexturaSolo;

/**
 *
 * @author gabri
 */
public class ValoresIdeaisGUI extends javax.swing.JFrame {

    /**
     * Creates new form ValoresIdeais
     */
    public ValoresIdeaisGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTitulo = new javax.swing.JLabel();
        rtFosforo = new javax.swing.JLabel();
        rtUnidadeFosforo = new javax.swing.JLabel();
        cxFosforoIdeal = new javax.swing.JTextField();
        rtPotassio = new javax.swing.JLabel();
        rtUnidadePotassio = new javax.swing.JLabel();
        cxPotassioIdeal = new javax.swing.JTextField();
        rtCalcio = new javax.swing.JLabel();
        rtUnidadeCalcio = new javax.swing.JLabel();
        cxCalcioIdeal = new javax.swing.JTextField();
        rtMagnesio = new javax.swing.JLabel();
        rtUnidadeMagnesio = new javax.swing.JLabel();
        cxMagnesioIdeal = new javax.swing.JTextField();
        rtEnxofre = new javax.swing.JLabel();
        rtUnidadeEnxofre = new javax.swing.JLabel();
        cxEnxofreIdeal = new javax.swing.JTextField();
        rtAluminio = new javax.swing.JLabel();
        cxAluminioIdeal = new javax.swing.JTextField();
        rtHAL = new javax.swing.JLabel();
        cxHALIdeal = new javax.swing.JTextField();
        btConsultar = new javax.swing.JButton();
        cbTipoSolo = new javax.swing.JComboBox<>();
        rtFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Valores Ideais");
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(null);

        rtTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        rtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        rtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtTitulo.setText("Valores Ideais");
        rtTitulo.setPreferredSize(new java.awt.Dimension(400, 75));
        getContentPane().add(rtTitulo);
        rtTitulo.setBounds(312, 6, 400, 75);

        rtFosforo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtFosforo.setForeground(new java.awt.Color(0, 0, 0));
        rtFosforo.setText("Fósforo");
        getContentPane().add(rtFosforo);
        rtFosforo.setBounds(120, 218, 64, 25);

        rtUnidadeFosforo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeFosforo.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeFosforo.setText("(mg.dm³)");
        getContentPane().add(rtUnidadeFosforo);
        rtUnidadeFosforo.setBounds(205, 222, 56, 20);

        cxFosforoIdeal.setEditable(false);
        cxFosforoIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxFosforoIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxFosforoIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxFosforoIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxFosforoIdeal);
        cxFosforoIdeal.setBounds(300, 218, 150, 30);

        rtPotassio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtPotassio.setForeground(new java.awt.Color(0, 0, 0));
        rtPotassio.setText("Potássio");
        getContentPane().add(rtPotassio);
        rtPotassio.setBounds(120, 266, 71, 25);

        rtUnidadePotassio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadePotassio.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadePotassio.setText("(cmol)");
        getContentPane().add(rtUnidadePotassio);
        rtUnidadePotassio.setBounds(209, 270, 37, 20);

        cxPotassioIdeal.setEditable(false);
        cxPotassioIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxPotassioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxPotassioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxPotassioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxPotassioIdeal);
        cxPotassioIdeal.setBounds(300, 266, 150, 30);

        rtCalcio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtCalcio.setForeground(new java.awt.Color(0, 0, 0));
        rtCalcio.setText("Cálcio");
        getContentPane().add(rtCalcio);
        rtCalcio.setBounds(120, 314, 51, 25);

        rtUnidadeCalcio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeCalcio.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeCalcio.setText("(cmol)");
        getContentPane().add(rtUnidadeCalcio);
        rtUnidadeCalcio.setBounds(209, 318, 37, 20);

        cxCalcioIdeal.setEditable(false);
        cxCalcioIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxCalcioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxCalcioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxCalcioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxCalcioIdeal);
        cxCalcioIdeal.setBounds(300, 314, 150, 30);

        rtMagnesio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtMagnesio.setForeground(new java.awt.Color(0, 0, 0));
        rtMagnesio.setText("Magnésio");
        getContentPane().add(rtMagnesio);
        rtMagnesio.setBounds(120, 362, 83, 25);

        rtUnidadeMagnesio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeMagnesio.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeMagnesio.setText("(cmol)");
        getContentPane().add(rtUnidadeMagnesio);
        rtUnidadeMagnesio.setBounds(209, 366, 37, 20);

        cxMagnesioIdeal.setEditable(false);
        cxMagnesioIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxMagnesioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxMagnesioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxMagnesioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxMagnesioIdeal);
        cxMagnesioIdeal.setBounds(300, 362, 150, 30);

        rtEnxofre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtEnxofre.setForeground(new java.awt.Color(0, 0, 0));
        rtEnxofre.setText("Enxofre");
        getContentPane().add(rtEnxofre);
        rtEnxofre.setBounds(120, 414, 66, 25);

        rtUnidadeEnxofre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtUnidadeEnxofre.setForeground(new java.awt.Color(0, 0, 0));
        rtUnidadeEnxofre.setText("(mg.dm³)");
        getContentPane().add(rtUnidadeEnxofre);
        rtUnidadeEnxofre.setBounds(205, 418, 56, 20);

        cxEnxofreIdeal.setEditable(false);
        cxEnxofreIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxEnxofreIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxEnxofreIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxEnxofreIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxEnxofreIdeal);
        cxEnxofreIdeal.setBounds(300, 414, 150, 30);

        rtAluminio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtAluminio.setForeground(new java.awt.Color(0, 0, 0));
        rtAluminio.setText("Alumínio");
        getContentPane().add(rtAluminio);
        rtAluminio.setBounds(120, 462, 77, 25);

        cxAluminioIdeal.setEditable(false);
        cxAluminioIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxAluminioIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxAluminioIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxAluminioIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxAluminioIdeal);
        cxAluminioIdeal.setBounds(300, 462, 150, 30);

        rtHAL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rtHAL.setForeground(new java.awt.Color(0, 0, 0));
        rtHAL.setText("H + AL");
        getContentPane().add(rtHAL);
        rtHAL.setBounds(120, 510, 59, 25);

        cxHALIdeal.setEditable(false);
        cxHALIdeal.setBackground(new java.awt.Color(204, 204, 204));
        cxHALIdeal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cxHALIdeal.setForeground(new java.awt.Color(0, 0, 0));
        cxHALIdeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(cxHALIdeal);
        cxHALIdeal.setBounds(300, 510, 150, 30);

        btConsultar.setBackground(new java.awt.Color(255, 255, 255));
        btConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btConsultar.setText("Consultar");
        btConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btConsultar.setPreferredSize(new java.awt.Dimension(84, 42));
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });
        btConsultar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btConsultarKeyPressed(evt);
            }
        });
        getContentPane().add(btConsultar);
        btConsultar.setBounds(600, 120, 150, 42);

        cbTipoSolo.setBackground(new java.awt.Color(255, 255, 255));
        cbTipoSolo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbTipoSolo.setForeground(new java.awt.Color(0, 0, 0));
        cbTipoSolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione um item abaixo>", "Solo Argiloso", "Solo Textura Média" }));
        getContentPane().add(cbTipoSolo);
        cbTipoSolo.setBounds(120, 120, 330, 42);

        rtFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Documentos\\UTFPR\\2021 - semestre 2\\Arquitetura de Software\\soilcorrectionCompleto\\soilcorrection\\src\\main\\java\\gui\\imagens\\background.png")); // NOI18N
        getContentPane().add(rtFundo);
        rtFundo.setBounds(-10, -10, 1050, 790);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btConsultarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btConsultarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoresIdeaisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoresIdeaisGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultar;
    private javax.swing.JComboBox<String> cbTipoSolo;
    private javax.swing.JTextField cxAluminioIdeal;
    private javax.swing.JTextField cxCalcioIdeal;
    private javax.swing.JTextField cxEnxofreIdeal;
    private javax.swing.JTextField cxFosforoIdeal;
    private javax.swing.JTextField cxHALIdeal;
    private javax.swing.JTextField cxMagnesioIdeal;
    private javax.swing.JTextField cxPotassioIdeal;
    private javax.swing.JLabel rtAluminio;
    private javax.swing.JLabel rtCalcio;
    private javax.swing.JLabel rtEnxofre;
    private javax.swing.JLabel rtFosforo;
    private javax.swing.JLabel rtFundo;
    private javax.swing.JLabel rtHAL;
    private javax.swing.JLabel rtMagnesio;
    private javax.swing.JLabel rtPotassio;
    private javax.swing.JLabel rtTitulo;
    private javax.swing.JLabel rtUnidadeCalcio;
    private javax.swing.JLabel rtUnidadeEnxofre;
    private javax.swing.JLabel rtUnidadeFosforo;
    private javax.swing.JLabel rtUnidadeMagnesio;
    private javax.swing.JLabel rtUnidadePotassio;
    // End of variables declaration//GEN-END:variables

    public void consultar(){
        String tipoSolo = cbTipoSolo.getSelectedItem().toString();
        switch(tipoSolo){
            case "Solo Argiloso":
                cxFosforoIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().fosforo()));
                cxPotassioIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().potassio()));
                cxCalcioIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().calcio()));
                cxMagnesioIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().magnesio()));
                cxEnxofreIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().enxofre()));
                cxAluminioIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().aluminio()));
                cxHALIdeal.setText(Double.toString(TexturaSolo.ARGILOSO.calculaValorIdeal().aluminioHidrogenio()));
                break;
            case "Solo Textura Média":
                cxFosforoIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().fosforo()));
                cxPotassioIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().potassio()));
                cxCalcioIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().calcio()));
                cxMagnesioIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().magnesio()));
                cxEnxofreIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().enxofre()));
                cxAluminioIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().aluminio()));
                cxHALIdeal.setText(Double.toString(TexturaSolo.TEXTURA_MEDIA.calculaValorIdeal().aluminioHidrogenio()));
                break;
            default:
                break;
        }
    }
}
